# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8229e9838cb3ea30c981f1971ca017323479c22716e0efa0972560026c6dc25c829869d0b3dad81d36a17a6d98db3c004b061ef354b676da4c0287888495a49f

test:
  secret_key_base: f222b2427829a60b528d8228797b75bd42434ca629515b56230f08baf9675e223d0d29c172631581707885439932b06f7d8cd6de579ea9f6d24f713398b7444b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
